services:
  - type: static
    name: ledl-web-repo-1
    publishPath: .
    staticPublishPath: .
    # Forzar que el servidor use index.html incluso si hay conflictos
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
